# Generated by Django 3.0.6 on 2020-05-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_repo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
