# Generated by Django 3.0.6 on 2020-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200522_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
